Fix conflict with similarly named dist:
Not upgrading because not running a local buildout command.
Uninstalling omelette.
Running uninstall recipe.
Uninstalling test.
Installing test.
Getting distribution for 'resonate[test]'.
zip_safe flag not set; analyzing archive contents...
resonate.html_maps: module references __file__
Got
Current directory is /home/rpatterson/src/work/sfu/purdue-engineering/src/resonate/
resonATe 0.3.2.
resonATe 0.3.2 does not provide the extra 'test'
While:
  Installing test.
Error: Couldn't find the required extra. This means the requirement is incorrect. If the requirement is itself from software you requested, then there might be a bug in requested software. You can ignore this by using 'allow-unknown-extras=true', however that may simply cause needed software to be omitted.